version: 2
registries:
  interlok:
    type: maven-repository
    url: https://nexus.adaptris.net/nexus/content/groups/interlok
    username: developer
    password: ${{secrets.NEXUS_REPO_PASSWORD}}

updates:
  - package-ecosystem: "gradle"
    directory: "/v4"
    registries:
      - "interlok"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    reviewers:
      - quotidian-ennui
      - mcwarman
      - aaron-mcgrath-adp
      - sebastien-belin-adp
      - higgyfella
  - package-ecosystem: "gradle"
    directory: "/v3"
    registries:
      - "public"
      - "interlok"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    reviewers:
      - quotidian-ennui
      - mcwarman
      - aaron-mcgrath-adp
      - sebastien-belin-adp
      - higgyfella